### ISSUE TITLE
[BUG] Global variables

### ISSUE THREAD

**Issue by RhinosF1** [quirc-bot/QuIRC#36]
**Describe the bug**
Traceback (most recent call last):
  File "bot.py", line 169, in <module>
    bot.run_loop()
  File "/home/t/tex/quirc/QuIRC-QuIRC-beta-1/QuIRC.py", line 139, in run_loop
    self.run_once()
  File "/home/t/tex/quirc/QuIRC-QuIRC-beta-1/QuIRC.py", line 89, in run_once
    event_handler(self, packet.arguments[0], packet.prefix.split("!")[0], packet.arguments[1])
  File "bot.py", line 113, in on_message
    if buttbot == 1:
UnboundLocalError: local variable 'buttbot' referenced before assignment

**Device (please complete the following information):**
 - Python Version 2.7
- Installed in own directory [yes]

**Additional context**
Partially fixed by 92ba5ab

**Comment by RhinosF1** [comment]
Closing -- BETA V1 IS NOW UNBLOCKED (BUG-WISE)
