### ISSUE TITLE
[FEATURE] Make Quotebot calculate how many quotes there is

### ISSUE THREAD

**Issue by RhinosF1** [quirc-bot/QuIRC#49]
**Is your feature request related to a problem? Please describe.**
Traceback (most recent call last):
  File "bot.py", line 307, in <module>
    bot.run_loop()
  File "/home/t/xxx/quirc/xxx_test/QuIRC.py", line 139, in run_loop
    self.run_once()
  File "/home/t/xxx/quirc/xxx_test/QuIRC.py", line 89, in run_once
    event_handler(self, packet.arguments[0], packet.prefix.split("!")[0], packet.arguments[1])
  File "bot.py", line 140, in on_message
    numq = int(numq)-1
ValueError: invalid literal for int() with base 10: ''
**Describe the solution you'd like**
Use len() to work out how many quotes it has to pick from itself

**Comment by sario528** [comment]
Fixed by #75
