### ISSUE TITLE
[BUG] bot crashes while trying to look up link titles

### ISSUE THREAD

**Issue by sario528** [quirc-bot/QuIRC#68]
Found link
Finding a title
<link title redacted>
Sending message...
message sent... logging..
Opened logs
Got timestamp
Traceback (most recent call last):
File "bot.py", line 343, in
bot.run_loop()
File "/<redacted>/QuIRC.py", line 139, in run_loop
self.run_once()
File "/<redacted>/QuIRC.py", line 89, in run_once
event_handler(self, packet.arguments[0], packet.prefix.split("!")[0], packet.arguments[1])
File "bot.py", line 127, in on_message
bot.send_message(channel, message)
File "/<redacted>/QuIRC.py", line 176, in send_message
logline = '\n [' + to + '] @ ' + st +' -' + botnick + ' : ' + message
TypeError: can only concatenate str (not "bytes") to str

**Comment by sario528** [comment]
Also weatherbot. Same error while trying to write to bot.log

**Comment by sario528** [comment]
Fixed in #76
